### ISSUE TITLE
Can we use this plugin to scan project source code (Java, .Net, Nodejs)

### ISSUE THREAD

**Issue by ravindrakmr** [turbot/steampipe-plugin-code#33]
Is it possible to scan project source code with this plugin ? Let's say I have a project whose source code is written in Java, can I use this plugin to scan that source code ? Just like -
select
  secret_type,
  secret,
  line,
  col
from
  code_secret
where
  src = Directory of my code base

If this feature is not available, is there any possibility to add support for it ?

**Comment by graza-io** [comment]
Hey @ravindrakmr 

I don't think at the current time it supports passing a directory into the `src` input.

That said, it is a good suggestion to allow for passing a directory and scanning the files within.

In the meantime as potential workaround since you can pass the file contents into `src` (based on [examples](https://hub.steampipe.io/plugins/turbot/code/tables/code_secret#examples)) you could always wrap a script around the CLI command to iterate each file and check them, or have this build a SQL query that unions the results together which you can then run.

**Comment by bigdatasourav** [comment]
Hey, @ravindrakmr, did the above workaround work for you? This item is still currently in our backlog. We're unsure exactly when the feature will be added to the plugin. Still, we'll leave the issue open in the meantime (we'd also appreciate any PRs if anyone wants to try developing the feature!).

**Comment by misraved** [comment]
Hello @ravindrakmr, we hope this message finds you well. We noticed that there hasn't been any recent activity on this issue, so we're planning to close it, for now, to help keep our records up to date. However, please don't hesitate to reopen it if you have any additional questions or if there's anything more we can assist you with. Thank you for your understanding.
